/**
 * HeatWatch - All-India Industrial Infrastructure & Thermal Catalog
 * Comprehensive database covering 50+ major industrial and environmental complexes
 * across India with coordinates, facility polygons, capacities, and baseline profiles.
 */

export const ALL_INDIA_FACILITIES = [
  // ==========================================
  // 1. REFINERIES & PETROCHEMICAL COMPLEXES
  // ==========================================
  {
    id: "REF-01",
    name: "Jamnagar Mega-Refinery & Cracker (RIL)",
    state: "Gujarat",
    city: "Moti Khavdi, Jamnagar",
    type: "Petrochemical & Refinery",
    coordinates: [22.3590, 69.8660],
    capacity: "1.24 Million BPD (68.2 MMTPA)",
    baselineFRP: 42.0,
    currentFRP: 68.4,
    status: "high_priority",
    operator: "Reliance Industries Ltd",
    units: "Crude Distillation, FCCU, Polypropylene Cracker, 8 Flare Stacks",
    landCover: { industrialBuiltUp: 76.4, bareSoilPaved: 15.2, waterBody: 5.1, vegetationTree: 3.3, cropland: 0.0 }
  },
  {
    id: "REF-02",
    name: "Nayara Energy Vadinar Refinery",
    state: "Gujarat",
    city: "Devbhumi Dwarka / Vadinar",
    type: "Petrochemical & Refinery",
    coordinates: [22.3950, 69.7210],
    capacity: "20 MMTPA (400,000 BPD)",
    baselineFRP: 36.5,
    currentFRP: 38.0,
    status: "normal",
    operator: "Nayara Energy (Rosneft JV)",
    units: "Delayed Coker, Hydrocracker, Sulfur Recovery, 4 Flares",
    landCover: { industrialBuiltUp: 71.0, bareSoilPaved: 22.0, waterBody: 5.0, vegetationTree: 2.0, cropland: 0.0 }
  },
  {
    id: "REF-03",
    name: "IOCL Panipat Refinery & Petrochemical Complex",
    state: "Haryana",
    city: "Panipat",
    type: "Petrochemical & Refinery",
    coordinates: [29.4720, 76.8850],
    capacity: "15 MMTPA (Expanding to 25 MMTPA)",
    baselineFRP: 45.0,
    currentFRP: 48.2,
    status: "normal",
    operator: "Indian Oil Corporation Ltd",
    units: "Naphtha Cracker, PTA Plant, PX Unit, Purified Terephthalic Acid",
    landCover: { industrialBuiltUp: 68.0, cropland: 24.0, bareSoilPaved: 6.0, vegetationTree: 2.0, waterBody: 0.0 }
  },
  {
    id: "REF-04",
    name: "IOCL Mathura Refinery",
    state: "Uttar Pradesh",
    city: "Mathura",
    type: "Petrochemical & Refinery",
    coordinates: [27.4280, 77.6890],
    capacity: "8.0 MMTPA",
    baselineFRP: 28.0,
    currentFRP: 29.5,
    status: "normal",
    operator: "Indian Oil Corporation Ltd",
    units: "FCCU, Diesel Hydro-treating, Sulfur Plant (TTZ Sensitive Zone)",
    landCover: { industrialBuiltUp: 62.0, cropland: 30.0, bareSoilPaved: 5.0, vegetationTree: 3.0, waterBody: 0.0 }
  },
  {
    id: "REF-05",
    name: "BPCL Mumbai Refinery (Mahul)",
    state: "Maharashtra",
    city: "Mumbai (Chembur/Mahul)",
    type: "Petrochemical & Refinery",
    coordinates: [19.0140, 72.8980],
    capacity: "12.0 MMTPA",
    baselineFRP: 32.0,
    currentFRP: 34.0,
    status: "normal",
    operator: "Bharat Petroleum Corporation Ltd",
    units: "Hydrocracker, Catalytic Reformer, High-Density Urban Buffer",
    landCover: { industrialBuiltUp: 84.0, waterBody: 12.0, bareSoilPaved: 4.0, vegetationTree: 0.0, cropland: 0.0 }
  },
  {
    id: "REF-06",
    name: "HPCL Mumbai Refinery",
    state: "Maharashtra",
    city: "Mumbai (Mahul)",
    type: "Petrochemical & Refinery",
    coordinates: [19.0080, 72.9020],
    capacity: "9.5 MMTPA",
    baselineFRP: 26.0,
    currentFRP: 27.2,
    status: "normal",
    operator: "Hindustan Petroleum Corporation Ltd",
    units: "Lube Base Oil Refinery, FCCU, Catalytic Cracking",
    landCover: { industrialBuiltUp: 86.0, waterBody: 10.0, bareSoilPaved: 4.0, vegetationTree: 0.0, cropland: 0.0 }
  },
  {
    id: "REF-07",
    name: "BPCL Kochi Refinery (Ambalamugal)",
    state: "Kerala",
    city: "Kochi",
    type: "Petrochemical & Refinery",
    coordinates: [9.9780, 76.3680],
    capacity: "15.5 MMTPA",
    baselineFRP: 31.0,
    currentFRP: 33.5,
    status: "normal",
    operator: "Bharat Petroleum Corporation Ltd",
    units: "Integrated Refinery Expansion Complex (IREP), Propylene Derivatives",
    landCover: { industrialBuiltUp: 65.0, vegetationTree: 25.0, waterBody: 8.0, bareSoilPaved: 2.0, cropland: 0.0 }
  },
  {
    id: "REF-08",
    name: "IOCL Paradip Mega-Refinery",
    state: "Odisha",
    city: "Paradip",
    type: "Petrochemical & Refinery",
    coordinates: [20.2880, 86.6340],
    capacity: "15.0 MMTPA",
    baselineFRP: 40.0,
    currentFRP: 42.0,
    status: "normal",
    operator: "Indian Oil Corporation Ltd",
    units: "INDMAX FCCU, Polypropylene, Dual Feed Cracker Complex",
    landCover: { industrialBuiltUp: 70.0, waterBody: 18.0, bareSoilPaved: 8.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "REF-09",
    name: "IOCL Haldia Refinery & Petrochemicals",
    state: "West Bengal",
    city: "Haldia",
    type: "Petrochemical & Refinery",
    coordinates: [22.0480, 88.0820],
    capacity: "8.0 MMTPA",
    baselineFRP: 30.0,
    currentFRP: 62.0,
    status: "elevated",
    operator: "Indian Oil Corporation Ltd / Haldia Petrochemicals",
    units: "Naphtha Cracker, Polymer Plants, Lube Oil Block, Port Terminal",
    landCover: { industrialBuiltUp: 74.0, waterBody: 16.0, bareSoilPaved: 6.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "REF-10",
    name: "HPCL Visakhapatnam Refinery",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    type: "Petrochemical & Refinery",
    coordinates: [17.6850, 83.2540],
    capacity: "15.0 MMTPA (Visakh Refinery Modernisation)",
    baselineFRP: 34.0,
    currentFRP: 36.0,
    status: "normal",
    operator: "Hindustan Petroleum Corporation Ltd",
    units: "Residue Upgradation Facility, Hydrogen Generation Units",
    landCover: { industrialBuiltUp: 78.0, waterBody: 12.0, bareSoilPaved: 6.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "REF-11",
    name: "HMEL Guru Gobind Singh Refinery (Bathinda)",
    state: "Punjab",
    city: "Bathinda",
    type: "Petrochemical & Refinery",
    coordinates: [29.9820, 75.0180],
    capacity: "11.3 MMTPA",
    baselineFRP: 33.0,
    currentFRP: 35.0,
    status: "normal",
    operator: "HPCL-Mittal Energy Ltd (HMEL)",
    units: "Dual Feed Polypropylene & Polyethylene Complex",
    landCover: { industrialBuiltUp: 64.0, cropland: 30.0, bareSoilPaved: 6.0, vegetationTree: 0.0, waterBody: 0.0 }
  },
  {
    id: "REF-12",
    name: "CPCL Manali Refinery (Chennai)",
    state: "Tamil Nadu",
    city: "Chennai (Manali)",
    type: "Petrochemical & Refinery",
    coordinates: [13.1650, 80.2620],
    capacity: "10.5 MMTPA",
    baselineFRP: 29.0,
    currentFRP: 31.0,
    status: "normal",
    operator: "Chennai Petroleum Corporation Ltd",
    units: "FCCU, Lube Plants, High Heavy Crude Processing",
    landCover: { industrialBuiltUp: 80.0, waterBody: 10.0, bareSoilPaved: 6.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "REF-13",
    name: "BPCL Bina Refinery",
    state: "Madhya Pradesh",
    city: "Bina (Sagar)",
    type: "Petrochemical & Refinery",
    coordinates: [24.1680, 78.1820],
    capacity: "7.8 MMTPA",
    baselineFRP: 27.0,
    currentFRP: 28.5,
    status: "normal",
    operator: "Bharat Petroleum Corporation Ltd",
    units: "Delayed Coker, Hydrocracker, Central India Distribution Hub",
    landCover: { industrialBuiltUp: 60.0, cropland: 32.0, bareSoilPaved: 6.0, vegetationTree: 2.0, waterBody: 0.0 }
  },
  {
    id: "REF-14",
    name: "IOCL Barauni Refinery",
    state: "Bihar",
    city: "Begusarai / Barauni",
    type: "Petrochemical & Refinery",
    coordinates: [25.4240, 85.9920],
    capacity: "6.0 MMTPA",
    baselineFRP: 24.0,
    currentFRP: 25.0,
    status: "normal",
    operator: "Indian Oil Corporation Ltd",
    units: "Atmospheric Distillation, Coking, Bitumen Units",
    landCover: { industrialBuiltUp: 58.0, cropland: 35.0, bareSoilPaved: 5.0, vegetationTree: 2.0, waterBody: 0.0 }
  },
  {
    id: "REF-15",
    name: "Numaligarh Refinery (Assam)",
    state: "Assam",
    city: "Golaghat / Numaligarh",
    type: "Petrochemical & Refinery",
    coordinates: [26.5840, 93.7480],
    capacity: "3.0 MMTPA (Expanding to 9 MMTPA)",
    baselineFRP: 22.0,
    currentFRP: 23.0,
    status: "normal",
    operator: "Numaligarh Refinery Ltd (NRL)",
    units: "Wax Plant, Hydrocracker, Kaziranga Buffer Proximity Monitoring",
    landCover: { industrialBuiltUp: 52.0, vegetationTree: 38.0, cropland: 6.0, waterBody: 4.0, bareSoilPaved: 0.0 }
  },

  // ==========================================
  // 2. SUPER THERMAL POWER STATIONS (COAL & GAS)
  // ==========================================
  {
    id: "PWR-01",
    name: "NTPC Vindhyachal Super Thermal Power Station",
    state: "Madhya Pradesh",
    city: "Singrauli / Vindhyanagar",
    type: "Thermal Power Station",
    coordinates: [24.0980, 82.6720],
    capacity: "4,760 MW (Largest Coal Plant in India)",
    baselineFRP: 65.0,
    currentFRP: 68.0,
    status: "normal",
    operator: "NTPC Limited",
    units: "13 Coal Generating Units (6x210MW + 7x500MW), Ash Dykes",
    landCover: { industrialBuiltUp: 72.0, bareSoilPaved: 18.0, waterBody: 6.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "PWR-02",
    name: "NTPC Korba Super Thermal Power Station",
    state: "Chhattisgarh",
    city: "Korba",
    type: "Thermal Power Station",
    coordinates: [22.3712, 82.6954],
    capacity: "2,600 MW",
    baselineFRP: 58.4,
    currentFRP: 112.5,
    status: "elevated",
    operator: "NTPC Limited",
    units: "7 Units (3x200MW + 4x500MW), Coal Conveyor & Ash Basin",
    landCover: { industrialBuiltUp: 68.2, bareSoilPaved: 18.3, vegetationTree: 9.1, waterBody: 4.4, cropland: 0.0 }
  },
  {
    id: "PWR-03",
    name: "NTPC Singrauli Super Thermal Power Station (Shaktinagar)",
    state: "Uttar Pradesh",
    city: "Sonbhadra / Shaktinagar",
    type: "Thermal Power Station",
    coordinates: [24.1120, 82.7840],
    capacity: "2,000 MW",
    baselineFRP: 52.0,
    currentFRP: 54.0,
    status: "normal",
    operator: "NTPC Limited",
    units: "5x200MW + 2x500MW, Rihand Reservoir Intake",
    landCover: { industrialBuiltUp: 66.0, waterBody: 20.0, bareSoilPaved: 10.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "PWR-04",
    name: "NTPC Sipat Super Thermal Power Station",
    state: "Chhattisgarh",
    city: "Bilaspur / Sipat",
    type: "Thermal Power Station",
    coordinates: [22.1320, 82.2850],
    capacity: "2,980 MW",
    baselineFRP: 56.0,
    currentFRP: 58.5,
    status: "normal",
    operator: "NTPC Limited",
    units: "Supercritical Boiler Technology (3x660MW + 2x500MW)",
    landCover: { industrialBuiltUp: 64.0, cropland: 26.0, bareSoilPaved: 6.0, vegetationTree: 4.0, waterBody: 0.0 }
  },
  {
    id: "PWR-05",
    name: "NTPC Ramagundam Super Thermal Power Station",
    state: "Telangana",
    city: "Peddapalli / Ramagundam",
    type: "Thermal Power Station",
    coordinates: [18.7560, 79.4520],
    capacity: "2,600 MW + 100 MW Floating Solar",
    baselineFRP: 54.0,
    currentFRP: 56.0,
    status: "normal",
    operator: "NTPC Limited",
    units: "7 Generating Units, Godavari River Cooling Water System",
    landCover: { industrialBuiltUp: 68.0, waterBody: 14.0, bareSoilPaved: 10.0, vegetationTree: 8.0, cropland: 0.0 }
  },
  {
    id: "PWR-06",
    name: "NTPC Talcher Super Thermal Power Station (Kaniha)",
    state: "Odisha",
    city: "Angul / Kaniha",
    type: "Thermal Power Station",
    coordinates: [21.0960, 85.0820],
    capacity: "3,000 MW",
    baselineFRP: 60.0,
    currentFRP: 62.0,
    status: "normal",
    operator: "NTPC Limited",
    units: "6x500MW Units, Lingaraj Coal Mine MGR Feeder",
    landCover: { industrialBuiltUp: 65.0, cropland: 20.0, bareSoilPaved: 10.0, vegetationTree: 5.0, waterBody: 0.0 }
  },
  {
    id: "PWR-07",
    name: "Mundra Ultra Mega Power Plant (Tata Power)",
    state: "Gujarat",
    city: "Kutch / Mundra",
    type: "Thermal Power Station",
    coordinates: [22.8180, 69.5250],
    capacity: "4,000 MW (5x800MW Supercritical)",
    baselineFRP: 62.0,
    currentFRP: 64.5,
    status: "normal",
    operator: "Coastal Gujarat Power Ltd (Tata)",
    units: "Imported Coal Boiler Island, Sea Water Cooling System",
    landCover: { industrialBuiltUp: 65.0, waterBody: 22.0, bareSoilPaved: 13.0, vegetationTree: 0.0, cropland: 0.0 }
  },
  {
    id: "PWR-08",
    name: "Adani Mundra Thermal Power Station",
    state: "Gujarat",
    city: "Kutch / Mundra",
    type: "Thermal Power Station",
    coordinates: [22.8250, 69.5540],
    capacity: "4,620 MW (4x330MW + 5x660MW)",
    baselineFRP: 64.0,
    currentFRP: 67.0,
    status: "normal",
    operator: "Adani Power Ltd",
    units: "Supercritical Coal Units, Deep-water Coal Unloading Jetty",
    landCover: { industrialBuiltUp: 70.0, waterBody: 18.0, bareSoilPaved: 12.0, vegetationTree: 0.0, cropland: 0.0 }
  },
  {
    id: "PWR-09",
    name: "Chandrapur Super Thermal Power Station (CSTPS)",
    state: "Maharashtra",
    city: "Chandrapur",
    type: "Thermal Power Station",
    coordinates: [19.9820, 79.2940],
    capacity: "2,920 MW",
    baselineFRP: 58.0,
    currentFRP: 61.0,
    status: "normal",
    operator: "Mahagenco",
    units: "Erai Dam Reservoir Cooling, Coal Stockyard Infrastructure",
    landCover: { industrialBuiltUp: 68.0, bareSoilPaved: 16.0, waterBody: 10.0, vegetationTree: 6.0, cropland: 0.0 }
  },
  {
    id: "PWR-10",
    name: "NTPC Dadri Power Complex (Coal & Gas)",
    state: "Uttar Pradesh",
    city: "Gautam Buddha Nagar / Dadri",
    type: "Thermal Power Station",
    coordinates: [28.6020, 77.5580],
    capacity: "2,637 MW (1820MW Coal + 817MW Gas)",
    baselineFRP: 46.0,
    currentFRP: 48.0,
    status: "normal",
    operator: "NTPC Limited",
    units: "Combined Cycle Gas Turbines & Coal Island, NCR Grid Node",
    landCover: { industrialBuiltUp: 66.0, cropland: 28.0, bareSoilPaved: 4.0, vegetationTree: 2.0, waterBody: 0.0 }
  },

  // ==========================================
  // 3. INTEGRATED STEEL & METALLURGY PLANTS
  // ==========================================
  {
    id: "STL-01",
    name: "Tata Steel Jamshedpur Works",
    state: "Jharkhand",
    city: "Jamshedpur",
    type: "Integrated Steel Plant",
    coordinates: [22.7880, 86.2080],
    capacity: "11 MMTPA Crude Steel",
    baselineFRP: 48.0,
    currentFRP: 51.0,
    status: "normal",
    operator: "Tata Steel Limited",
    units: "Blast Furnaces (I & H), LD Steel Melt Shop, Coke Ovens, Sinter Plants",
    landCover: { industrialBuiltUp: 82.0, bareSoilPaved: 10.0, vegetationTree: 6.0, waterBody: 2.0, cropland: 0.0 }
  },
  {
    id: "STL-02",
    name: "SAIL Bhilai Steel Plant",
    state: "Chhattisgarh",
    city: "Bhilai / Durg",
    type: "Integrated Steel Plant",
    coordinates: [21.1850, 81.3980],
    capacity: "7.0 MMTPA",
    baselineFRP: 44.0,
    currentFRP: 46.0,
    status: "normal",
    operator: "Steel Authority of India Ltd (SAIL)",
    units: "Blast Furnace #8 (Mahamaya), Rail & Heavy Structurals Mill",
    landCover: { industrialBuiltUp: 78.0, bareSoilPaved: 14.0, vegetationTree: 6.0, waterBody: 2.0, cropland: 0.0 }
  },
  {
    id: "STL-03",
    name: "SAIL Bokaro Steel Plant",
    state: "Jharkhand",
    city: "Bokaro Steel City",
    type: "Integrated Steel Plant",
    coordinates: [23.6720, 86.1480],
    capacity: "5.8 MMTPA",
    baselineFRP: 42.0,
    currentFRP: 45.0,
    status: "normal",
    operator: "Steel Authority of India Ltd (SAIL)",
    units: "5 Blast Furnaces, Continuous Casting Shop, Hot Strip Mill",
    landCover: { industrialBuiltUp: 76.0, bareSoilPaved: 15.0, vegetationTree: 6.0, waterBody: 3.0, cropland: 0.0 }
  },
  {
    id: "STL-04",
    name: "SAIL Rourkela Steel Plant",
    state: "Odisha",
    city: "Rourkela (Sundargarh)",
    type: "Integrated Steel Plant",
    coordinates: [22.2240, 84.8680],
    capacity: "4.5 MMTPA",
    baselineFRP: 39.0,
    currentFRP: 41.5,
    status: "normal",
    operator: "Steel Authority of India Ltd (SAIL)",
    units: "Blast Furnace (Durga), Plate Mill, Special Steel for Defence",
    landCover: { industrialBuiltUp: 74.0, bareSoilPaved: 16.0, vegetationTree: 8.0, waterBody: 2.0, cropland: 0.0 }
  },
  {
    id: "STL-05",
    name: "JSW Steel Vijayanagar Works (Toranagallu)",
    state: "Karnataka",
    city: "Ballari / Toranagallu",
    type: "Integrated Steel Plant",
    coordinates: [15.1850, 76.6620],
    capacity: "12.0 MMTPA (Expanding to 18 MMTPA)",
    baselineFRP: 52.0,
    currentFRP: 55.0,
    status: "normal",
    operator: "JSW Steel Limited",
    units: "COREX Iron-making, Largest Blast Furnace in India, Pellet Plants",
    landCover: { industrialBuiltUp: 80.0, bareSoilPaved: 14.0, vegetationTree: 4.0, waterBody: 2.0, cropland: 0.0 }
  },
  {
    id: "STL-06",
    name: "Tata Steel Kalinganagar",
    state: "Odisha",
    city: "Jajpur / Kalinganagar",
    type: "Integrated Steel Plant",
    coordinates: [20.9580, 86.0120],
    capacity: "8.0 MMTPA",
    baselineFRP: 46.0,
    currentFRP: 49.0,
    status: "normal",
    operator: "Tata Steel Limited",
    units: "State-of-the-art BF & HSM, Heavy industrial corridor",
    landCover: { industrialBuiltUp: 72.0, bareSoilPaved: 18.0, vegetationTree: 6.0, cropland: 4.0, waterBody: 0.0 }
  },
  {
    id: "STL-07",
    name: "Rashtriya Ispat Nigam Ltd (RINL / Vizag Steel)",
    state: "Andhra Pradesh",
    city: "Visakhapatnam",
    type: "Integrated Steel Plant",
    coordinates: [17.6250, 83.1850],
    capacity: "7.3 MMTPA",
    baselineFRP: 40.0,
    currentFRP: 43.0,
    status: "normal",
    operator: "RINL (Govt of India)",
    units: "Shore-based Steel Plant, Coke Oven Battery, Sinter Plant",
    landCover: { industrialBuiltUp: 75.0, waterBody: 15.0, bareSoilPaved: 6.0, vegetationTree: 4.0, cropland: 0.0 }
  },
  {
    id: "STL-08",
    name: "AM/NS India Hazira Steel Complex",
    state: "Gujarat",
    city: "Surat / Hazira",
    type: "Integrated Steel Plant",
    coordinates: [21.1120, 72.6780],
    capacity: "9.6 MMTPA",
    baselineFRP: 43.0,
    currentFRP: 45.0,
    status: "normal",
    operator: "ArcelorMittal Nippon Steel (AM/NS)",
    units: "Direct Reduced Iron (DRI), Electric Arc Furnace, Corex Plants",
    landCover: { industrialBuiltUp: 81.0, waterBody: 12.0, bareSoilPaved: 5.0, vegetationTree: 2.0, cropland: 0.0 }
  },

  // ==========================================
  // 4. COAL MINES & SUBSURFACE FIRE BASINS
  // ==========================================
  {
    id: "MINE-01",
    name: "Jharia Coalfield Subsurface Mine Fires",
    state: "Jharkhand",
    city: "Dhanbad / Jharia",
    type: "Coal Mining & Subsurface Fire Basin",
    coordinates: [23.7420, 86.4150],
    capacity: "Over 60 Active Mine Fire Zones",
    baselineFRP: 55.0,
    currentFRP: 135.0,
    status: "high_priority",
    operator: "Bharat Coking Coal Ltd (BCCL)",
    units: "Century-old subterranean coal seam oxidation, subsidence trenches",
    landCover: { bareSoilPaved: 78.0, industrialBuiltUp: 16.0, vegetationTree: 4.0, waterBody: 2.0, cropland: 0.0 }
  },
  {
    id: "MINE-02",
    name: "Korba Gevra Open-Cast Coal Mine (Largest in Asia)",
    state: "Chhattisgarh",
    city: "Korba / Gevra",
    type: "Open-Cast Coal Mine",
    coordinates: [22.3380, 82.5920],
    capacity: "50+ MMTPA Coal Extraction",
    baselineFRP: 35.0,
    currentFRP: 38.0,
    status: "normal",
    operator: "South Eastern Coalfields Ltd (SECL)",
    units: "Dragline extraction benches, in-pit crushing & conveyor system",
    landCover: { bareSoilPaved: 74.0, industrialBuiltUp: 18.0, vegetationTree: 6.0, cropland: 2.0, waterBody: 0.0 }
  },
  {
    id: "MINE-03",
    name: "Singrauli Jayant Open-Cast Coal Mine",
    state: "Madhya Pradesh",
    city: "Singrauli / Jayant",
    type: "Open-Cast Coal Mine",
    coordinates: [24.1845, 82.6482],
    capacity: "15 MMTPA Coal",
    baselineFRP: 32.0,
    currentFRP: 74.5,
    status: "elevated",
    operator: "Northern Coalfields Ltd (NCL)",
    units: "Active coal bench #1-4, spontaneous coal auto-oxidation flare",
    landCover: { bareSoilPaved: 72.4, industrialBuiltUp: 21.0, vegetationTree: 6.6, cropland: 0.0, waterBody: 0.0 }
  },
  {
    id: "MINE-04",
    name: "Raniganj Coalfield Fire & Mining Belt",
    state: "West Bengal",
    city: "Asansol / Raniganj",
    type: "Coal Mining Complex",
    coordinates: [23.6200, 87.1200],
    capacity: "Eastern Coalfields Heritage Mines",
    baselineFRP: 38.0,
    currentFRP: 42.0,
    status: "normal",
    operator: "Eastern Coalfields Ltd (ECL)",
    units: "Underground & open-cast pits, abandoned mine fire monitoring",
    landCover: { bareSoilPaved: 66.0, industrialBuiltUp: 22.0, vegetationTree: 8.0, cropland: 4.0, waterBody: 0.0 }
  },
  {
    id: "MINE-05",
    name: "Bailadila Iron Ore Mining Complex (Deposit 14/11)",
    state: "Chhattisgarh",
    city: "Dantewada / Kirandul",
    type: "Open-Cast Iron Ore Mine",
    coordinates: [18.6650, 81.2480],
    capacity: "30 MMTPA High-Grade Iron Ore",
    baselineFRP: 20.0,
    currentFRP: 22.0,
    status: "normal",
    operator: "NMDC Limited",
    units: "Hilltop open pit extraction, ore processing & slurry pipelines",
    landCover: { bareSoilPaved: 60.0, vegetationTree: 30.0, industrialBuiltUp: 10.0, cropland: 0.0, waterBody: 0.0 }
  },

  // ==========================================
  // 5. CHEMICAL & SPECIAL PETROCHEMICAL ZONES
  // ==========================================
  {
    id: "CHEM-01",
    name: "Dahej Petroleum, Chemicals & Petrochemicals Investment Region (PCPIR)",
    state: "Gujarat",
    city: "Bharuch / Dahej",
    type: "Chemical & Industrial Estate",
    coordinates: [21.7120, 72.5850],
    capacity: "453 Sq Km Megazone (OPaL, GNFC, Petronet LNG)",
    baselineFRP: 40.0,
    currentFRP: 43.0,
    status: "normal",
    operator: "ONGC Petro additions Ltd (OPaL) / GIDC",
    units: "Dual Feed Cracker Unit (1.1 MMTPA Ethylene), LNG Regas Terminal",
    landCover: { industrialBuiltUp: 78.0, waterBody: 14.0, bareSoilPaved: 8.0, vegetationTree: 0.0, cropland: 0.0 }
  },
  {
    id: "CHEM-02",
    name: "Ankleshwar Chemical Industrial Estate (GIDC)",
    state: "Gujarat",
    city: "Ankleshwar",
    type: "Chemical & Industrial Estate",
    coordinates: [21.6280, 73.0120],
    capacity: "1,500+ Chemical & Pharma Units",
    baselineFRP: 28.0,
    currentFRP: 31.0,
    status: "normal",
    operator: "Gujarat Industrial Development Corporation",
    units: "Dyes, Pigments, Pharmaceuticals, Centralized Effluent Incineration",
    landCover: { industrialBuiltUp: 85.0, bareSoilPaved: 10.0, cropland: 3.0, vegetationTree: 2.0, waterBody: 0.0 }
  },
  {
    id: "CHEM-03",
    name: "Hazira Heavy Industrial Zone (Shell/Total LNG & L&T)",
    state: "Gujarat",
    city: "Surat / Hazira",
    type: "LNG & Heavy Chemical Port",
    coordinates: [21.0945, 72.6682],
    capacity: "5 MMTPA LNG Regas + Cryogenic Storage",
    baselineFRP: 35.8,
    currentFRP: 38.2,
    status: "normal",
    operator: "Shell / TotalEnergies / L&T Heavy Eng",
    units: "Cryogenic Tanks, Gas Flares, Heavy Modular Fabrication Yard",
    landCover: { industrialBuiltUp: 82.1, waterBody: 14.5, bareSoilPaved: 3.4, vegetationTree: 0.0, cropland: 0.0 }
  },

  // ==========================================
  // 6. ECOLOGICAL & FORESTRY MONITORING HUBS
  // ==========================================
  {
    id: "FOR-01",
    name: "Simlipal Biosphere Reserve Core & Buffer",
    state: "Odisha",
    city: "Mayurbhanj / Baripada",
    type: "Protected Biosphere Reserve",
    coordinates: [21.8651, 86.3294],
    capacity: "2,750 Sq Km Deciduous Forest Canopy",
    baselineFRP: 12.0,
    currentFRP: 340.8,
    status: "high_priority",
    operator: "Odisha Forest Department & ODRAF",
    units: "Tiger Reserve, Dense Sal Canopy, Fast-moving seasonal fireline",
    landCover: { vegetationTree: 88.4, shrubland: 7.2, cropland: 3.1, bareSoilPaved: 1.3, industrialBuiltUp: 0.0 }
  },
  {
    id: "FOR-02",
    name: "Bandhavgarh National Park Forest Zone",
    state: "Madhya Pradesh",
    city: "Umaria",
    type: "Protected Natural Forest",
    coordinates: [23.7020, 81.0250],
    capacity: "1,536 Sq Km Protected Forest",
    baselineFRP: 8.0,
    currentFRP: 9.2,
    status: "normal",
    operator: "MP Forest Department",
    units: "Moist deciduous forest, seasonal leaf-litter fire tracking",
    landCover: { vegetationTree: 85.0, shrubland: 10.0, cropland: 4.0, bareSoilPaved: 1.0, industrialBuiltUp: 0.0 }
  },
  {
    id: "FOR-03",
    name: "Garhwal Himalayan Pine Forest Fire Corridor",
    state: "Uttarakhand",
    city: "Pauri / Chamoli",
    type: "Protected Mountain Forest",
    coordinates: [30.1500, 78.8000],
    capacity: "Chir Pine Forest Elevation Belt",
    baselineFRP: 15.0,
    currentFRP: 18.0,
    status: "normal",
    operator: "Uttarakhand Forest Fire Disaster Wing",
    units: "Resin-rich Pine needles, steep slope thermal propagation",
    landCover: { vegetationTree: 82.0, bareSoilPaved: 12.0, shrubland: 6.0, cropland: 0.0, industrialBuiltUp: 0.0 }
  },

  // ==========================================
  // 7. AGRARIAN CROP STUBBLE BURNING CORRIDORS
  // ==========================================
  {
    id: "AGR-01",
    name: "Patiala & Sangrur Paddy Stubble Burning Belt",
    state: "Punjab",
    city: "Patiala / Sangrur",
    type: "Agrarian Cropland Matrix",
    coordinates: [30.3456, 76.4120],
    capacity: "Major Post-Harvest Stubble Corridor",
    baselineFRP: 15.2,
    currentFRP: 48.0,
    status: "normal",
    operator: "Punjab Pollution Control Board (PPCB)",
    units: "Seasonal Paddy Field Straw Burning, Short-lived Ephemeral Fires",
    landCover: { cropland: 91.5, industrialBuiltUp: 4.2, vegetationTree: 3.1, bareSoilPaved: 1.2, waterBody: 0.0 }
  },
  {
    id: "AGR-02",
    name: "Ludhiana & Khanna Agro-Industrial Burning Cluster",
    state: "Punjab",
    city: "Ludhiana / Khanna",
    type: "Agrarian Cropland Matrix",
    coordinates: [30.7050, 75.8500],
    capacity: "Wheat-Paddy Crop Rotation Zone",
    baselineFRP: 16.0,
    currentFRP: 42.0,
    status: "normal",
    operator: "State Pollution Control Board",
    units: "Agricultural residue fires, farm parcel boundaries",
    landCover: { cropland: 88.0, industrialBuiltUp: 7.0, vegetationTree: 3.0, bareSoilPaved: 2.0, waterBody: 0.0 }
  },
  {
    id: "AGR-03",
    name: "Karnal & Kaithal Stubble Belt",
    state: "Haryana",
    city: "Karnal / Kaithal",
    type: "Agrarian Cropland Matrix",
    coordinates: [29.6850, 76.9900],
    capacity: "Upper Indo-Gangetic Plains Farm Grid",
    baselineFRP: 14.0,
    currentFRP: 36.0,
    status: "normal",
    operator: "Haryana State Pollution Control Board",
    units: "Post-harvest crop residue burns, NCR air corridor",
    landCover: { cropland: 90.0, industrialBuiltUp: 5.0, vegetationTree: 3.0, bareSoilPaved: 2.0, waterBody: 0.0 }
  }
];
